### PR TITLE
day 3

### PR DESCRIPTION
**Pull request by motunrayokoyejo**

### CODE REVIEW

**Review by emetowinner — CHANGES_REQUESTED** [review]
Please name your folder that contains your daily solutions properly, your folder is named Day 2 while your PR is saying Day 3

**Review by motunrayokoyejo — COMMENTED** [review]
It contains both challenge solutions for day 2 and day 3

**Comment by emetowinner** [comment]
Please resolve this conflict so I can merge

**Comment by motunrayokoyejo** [comment]
How do I change my commit message?

**Comment by emetowinner** [comment]
Close this pull request, go back to your system and run git fetch upstream
and git pull origin master.

**Comment by motunrayokoyejo** [comment]
Okay, Thank you so much.

**Pull request closed without merging**
